// Seed data — mirrors src/types/index.ts SAMPLE_STAFF + SAMPLE_SHIFTS
export const SEED_STAFF = [
  { id: 's1',  name: 'Alex Rivera',   role: 'Manager',   department: 'Management', color: '#8b5cf6', status: 'active',   hoursPerWeek: 40, email: 'alex@nyxgrid.io'   },
  { id: 's2',  name: 'Jordan Lee',    role: 'Supervisor', department: 'Management', color: '#6366f1', status: 'active',   hoursPerWeek: 40, email: 'jordan@nyxgrid.io'  },
  { id: 's3',  name: 'Casey Morgan',  role: 'Barista',   department: 'Bar',        color: '#0ea5e9', status: 'active',   hoursPerWeek: 32, email: 'casey@nyxgrid.io'   },
  { id: 's4',  name: 'Taylor Brooks', role: 'Barista',   department: 'Bar',        color: '#06b6d4', status: 'active',   hoursPerWeek: 24, email: 'taylor@nyxgrid.io'  },
  { id: 's5',  name: 'Sam Nguyen',    role: 'Cook',      department: 'Kitchen',    color: '#f97316', status: 'active',   hoursPerWeek: 40, email: 'sam@nyxgrid.io'     },
  { id: 's6',  name: 'Morgan Davis',  role: 'Line Cook', department: 'Kitchen',    color: '#f59e0b', status: 'active',   hoursPerWeek: 36, email: 'morgan@nyxgrid.io'  },
  { id: 's7',  name: 'Riley Chen',    role: 'Server',    department: 'FOH',        color: '#10b981', status: 'active',   hoursPerWeek: 28, email: 'riley@nyxgrid.io'   },
  { id: 's8',  name: 'Drew Wilson',   role: 'Server',    department: 'FOH',        color: '#14b8a6', status: 'active',   hoursPerWeek: 32, email: 'drew@nyxgrid.io'    },
  { id: 's9',  name: 'Jamie Park',    role: 'Host',      department: 'FOH',        color: '#84cc16', status: 'active',   hoursPerWeek: 20, email: 'jamie@nyxgrid.io'   },
  { id: 's10', name: 'Avery Kim',     role: 'Dishwasher', department: 'Kitchen',   color: '#f43f5e', status: 'active',   hoursPerWeek: 20, email: 'avery@nyxgrid.io'   },
  { id: 's11', name: 'Chris Okafor',  role: 'Delivery',  department: 'Delivery',   color: '#d946ef', status: 'on-leave', hoursPerWeek: 30, email: 'chris@nyxgrid.io'   },
  { id: 's12', name: 'Dana Flores',   role: 'Part-time', department: 'FOH',        color: '#ec4899', status: 'active',   hoursPerWeek: 16, email: 'dana@nyxgrid.io'    },
]

export const SEED_SHIFTS = [
  { id: 'sh1',  staffId: 's1',  day: 'Mon', startTime: '09:00', endTime: '17:00', position: 'Open'    },
  { id: 'sh2',  staffId: 's1',  day: 'Tue', startTime: '09:00', endTime: '17:00', position: 'Open'    },
  { id: 'sh3',  staffId: 's1',  day: 'Wed', startTime: '09:00', endTime: '17:00', position: 'Open'    },
  { id: 'sh4',  staffId: 's2',  day: 'Thu', startTime: '12:00', endTime: '20:00', position: 'Mid'     },
  { id: 'sh5',  staffId: 's2',  day: 'Fri', startTime: '12:00', endTime: '20:00', position: 'Mid'     },
  { id: 'sh6',  staffId: 's3',  day: 'Mon', startTime: '07:00', endTime: '15:00', position: 'Bar'     },
  { id: 'sh7',  staffId: 's3',  day: 'Wed', startTime: '07:00', endTime: '15:00', position: 'Bar'     },
  { id: 'sh8',  staffId: 's3',  day: 'Fri', startTime: '07:00', endTime: '15:00', position: 'Bar'     },
  { id: 'sh9',  staffId: 's4',  day: 'Tue', startTime: '14:00', endTime: '22:00', position: 'Bar'     },
  { id: 'sh10', staffId: 's4',  day: 'Thu', startTime: '14:00', endTime: '22:00', position: 'Bar'     },
  { id: 'sh11', staffId: 's4',  day: 'Sat', startTime: '10:00', endTime: '18:00', position: 'Bar'     },
  { id: 'sh12', staffId: 's5',  day: 'Mon', startTime: '10:00', endTime: '18:00', position: 'Kitchen' },
  { id: 'sh13', staffId: 's5',  day: 'Tue', startTime: '10:00', endTime: '18:00', position: 'Kitchen' },
  { id: 'sh14', staffId: 's5',  day: 'Thu', startTime: '10:00', endTime: '18:00', position: 'Kitchen' },
  { id: 'sh15', staffId: 's5',  day: 'Fri', startTime: '10:00', endTime: '18:00', position: 'Kitchen' },
  { id: 'sh16', staffId: 's6',  day: 'Wed', startTime: '14:00', endTime: '22:00', position: 'Kitchen' },
  { id: 'sh17', staffId: 's6',  day: 'Sat', startTime: '14:00', endTime: '22:00', position: 'Kitchen' },
  { id: 'sh18', staffId: 's6',  day: 'Sun', startTime: '10:00', endTime: '18:00', position: 'Kitchen' },
  { id: 'sh19', staffId: 's7',  day: 'Fri', startTime: '16:00', endTime: '23:00', position: 'FOH'     },
  { id: 'sh20', staffId: 's7',  day: 'Sat', startTime: '16:00', endTime: '23:00', position: 'FOH'     },
  { id: 'sh21', staffId: 's7',  day: 'Sun', startTime: '12:00', endTime: '20:00', position: 'FOH'     },
  { id: 'sh22', staffId: 's8',  day: 'Mon', startTime: '16:00', endTime: '23:00', position: 'FOH'     },
  { id: 'sh23', staffId: 's8',  day: 'Tue', startTime: '16:00', endTime: '23:00', position: 'FOH'     },
  { id: 'sh24', staffId: 's8',  day: 'Wed', startTime: '16:00', endTime: '23:00', position: 'FOH'     },
  { id: 'sh25', staffId: 's9',  day: 'Sat', startTime: '11:00', endTime: '19:00', position: 'FOH'     },
  { id: 'sh26', staffId: 's9',  day: 'Sun', startTime: '11:00', endTime: '19:00', position: 'FOH'     },
  { id: 'sh27', staffId: 's10', day: 'Fri', startTime: '17:00', endTime: '23:00', position: 'Kitchen' },
  { id: 'sh28', staffId: 's10', day: 'Sat', startTime: '17:00', endTime: '23:00', position: 'Kitchen' },
  { id: 'sh29', staffId: 's12', day: 'Sat', startTime: '12:00', endTime: '20:00', position: 'FOH'     },
  { id: 'sh30', staffId: 's12', day: 'Sun', startTime: '12:00', endTime: '20:00', position: 'FOH'     },
]
